import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const owner = '00000000-0000-4000-8000-000000000001';
const admin = '00000000-0000-4000-8000-000000000002';
const student = '00000000-0000-4000-8000-000000000003';
const hash = 'a'.repeat(64);
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth,public to anon,authenticated,service_role;`);
await db.exec(await readFile(new URL('../supabase/schema.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_platform.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_privacy.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_sports.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_team_save.sql', import.meta.url), 'utf8'));
await db.exec(`insert into auth.users values('${owner}'),('${admin}'),('${student}'); insert into public.account_controls(user_id,is_admin,is_owner) values('${owner}',true,true),('${admin}',true,false); insert into public.suggestions(category,message,session_hash) values('Outro','Mensagem de teste privada','${hash}');`);
async function as(role, id = '') { await db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub','${id}',false);`); }
async function rejects(sql, params = []) { await assert.rejects(db.query(sql, params)); checks++; }
async function scalar(sql, params = []) { return Object.values((await db.query(sql, params)).rows[0])[0]; }
await as('anon');
assert.equal(await scalar('select count(*) from public.team_members'), 0); checks++;
assert.equal(await scalar('select count(*) from public.proposal_progress'), 1); checks++;
await rejects('select * from public.suggestions');
await rejects('select * from public.vote_intentions');
await rejects('select public.vote_summary()');
await rejects('select public.record_intention($1)', [hash]);
await rejects('select public.consume_rate($1,1,60)', ['x']);
await rejects("insert into public.team_members(name,position) values('Ataque',0)");
await as('authenticated', student);
assert.equal(await scalar('select count(*) from public.suggestions'), 0); checks++;
await rejects('select public.replace_team($1::jsonb)', ['["Ataque"]']);
await rejects('select public.vote_summary()');
await rejects('update public.account_controls set is_admin=true where user_id=$1', [student]);
await db.query("insert into public.proposal_progress(proposal_id,stage) values(1,'Realizada')").then(() => { throw new Error('Unauthorized mutation succeeded'); }, () => checks++);
await as('authenticated', admin);
assert.equal(await scalar('select count(*) from public.suggestions'), 1); checks++;
await db.query('select public.replace_team($1::jsonb)', ['["Nome autorizado de teste","Outro nome autorizado"]']); checks++;
assert.equal(await scalar('select count(*) from public.team_members'), 2); checks++;
await rejects('select public.replace_team($1::jsonb)', ['["<script>"]']);
assert.equal(await scalar('select count(*) from public.team_members'), 2); checks++;
await rejects("update public.suggestions set message='Conteúdo alterado'");
await db.query("update public.suggestions set status='analisada'"); checks++;
await rejects('select public.manage_account($1,true,false,null,$2)', [student, 'Permissão de teste']);
await as('service_role');
const results = await Promise.all(Array.from({ length: 10 }, () => scalar('select public.record_intention($1)', [hash])));
assert.equal(results.filter(Boolean).length, 1); checks++;
assert.equal(await scalar('select count(*) from public.vote_intentions'), 1); checks++;
assert.equal(await scalar('select public.consume_rate($1,1,60)', ['test-bucket']), true); checks++;
assert.equal(await scalar('select public.consume_rate($1,1,60)', ['test-bucket']), false); checks++;
await as('authenticated', owner);
const summary = await scalar('select public.vote_summary()');
assert.equal(summary.ft_intentions, 1); assert.equal(summary.student_total, 310); assert.equal(summary.opposition_reported, 80); assert.equal(summary.unrepresented_estimate, 229); checks += 4;
await db.query('select public.manage_account($1,true,true,null,$2)', [admin, 'Bloqueio justificado de teste']); checks++;
await rejects('select public.manage_account($1,false,true,null,$2)', [owner, 'Tentativa de alterar proprietário']);
await as('authenticated', admin);
assert.equal(await scalar('select public.is_admin()'), false); checks++;
assert.equal(await scalar('select count(*) from public.suggestions'), 0); checks++;
await rejects('select public.vote_summary()');
await as('authenticated', owner);
await db.query('select public.suspend_session($1,now()+interval\'1 day\',$2)', [hash, 'Spam de teste']); checks++;
await rejects('select public.suspend_session($1,now()+interval\'31 days\',$2)', [hash, 'Tempo inválido']);
await rejects("insert into public.proposal_progress(proposal_id,stage) values(36,'Apresentada')");
await as('anon');
assert.equal(await scalar('select count(*) from public.proposal_classifications where priority'), 5); checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications where early'), 8); checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications where sport'), 2); checks++;
await rejects('select * from public.election_2026');
await rejects('select public.save_election($1,true)', ['{"status":"eleita"}']);
await as('authenticated',student);
await db.query('update public.proposal_classifications set sport=true where proposal_id=1');
assert.equal(await scalar('select sport from public.proposal_classifications where proposal_id=1'),false);checks++;
await db.query('update public.proposal_classifications set priority=true where proposal_id=31');
assert.equal(await scalar('select priority from public.proposal_classifications where proposal_id=31'),false);checks++;
await rejects("insert into public.project_records(kind,category,title,description) values('talentos','Música','Teste','Trabalho privado de teste')");
await as('authenticated',owner);
await db.query("insert into public.project_records(kind,category,title,description) values('talentos','Música','Rascunho','Trabalho privado de teste')");checks++;
await rejects("update public.project_records set published=true");
await as('anon');
assert.equal(await scalar('select count(*) from public.project_records'),0); checks++;
const hidden=await scalar('select public.election_public()');
if(Date.now()<Date.parse('2026-10-13T03:00:00Z')){assert.equal(hidden.visible,false);assert.equal(hidden.intentions,undefined);checks+=2;}
await as('authenticated',owner);
await db.query("update public.project_records set consent_confirmed=true,published=true");checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.project_records'),1);checks++;
await as('authenticated',owner);
await rejects('select public.save_election($1,true)',['{"status":"eleita","source":"Escola"}']);
await as('service_role');
await db.query("update public.election_2026 set status='eleita',confirmed_at=now(),source='Registro de teste da escola',published_at=now()");
await rejects('select public.record_intention($1)',['b'.repeat(64)]);
assert.equal(await scalar('select count(*) from public.vote_intentions'),1); checks++;
await as('anon'); await rejects('select public.erase_suggestion(gen_random_uuid(),true)');
await as('authenticated',student); await rejects('select public.erase_suggestion(gen_random_uuid(),true)');
await as('authenticated',owner);
const suggestionId = await scalar('select id from public.suggestions limit 1');
await rejects('select public.erase_suggestion($1,false)',[suggestionId]);
assert.equal(await scalar('select public.erase_suggestion($1,true)',[suggestionId]),true); checks++;
assert.equal(await scalar('select count(*) from public.suggestions'),0); checks++;
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261009_central.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_planning_drafts.sql',import.meta.url),'utf8'));
await as('anon');
assert.equal(await scalar('select count(*) from public.proposal_catalogue'),35);checks++;
assert.equal(await scalar('select count(*) from public.proposal_catalogue where id>=36'),0);checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications'),35);checks++;
await rejects("insert into public.management_records(kind,title,body) values('return','Teste','Resumo privado de teste')");
await as('authenticated',student);
await db.query("update public.proposal_catalogue set editorial_state='Publicada' where id=36");
assert.equal(await scalar('select count(*) from public.proposal_catalogue'),35);checks++;
await rejects("insert into public.ft_projects(title,description,category) values('Ataque','Texto de teste inválido','Teste')");
await as('authenticated',owner);
assert.equal(await scalar('select count(*) from public.proposal_catalogue'),45);checks++;
assert.equal(await scalar("select count(*) from public.proposal_catalogue where editorial_state='Aguardando aprovação da equipe'"),10);checks++;
await rejects("update public.proposal_catalogue set editorial_state='Rascunho' where id=1");
await rejects('delete from public.proposal_catalogue where id=1');
await rejects("update public.proposal_catalogue set title='<script>' where id=36");
await db.query("update public.proposal_catalogue set editorial_state='Aprovada pela equipe' where id=36");
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue'),35);checks++;
await as('authenticated',owner);
await db.query("update public.proposal_catalogue set editorial_state='Publicada' where id=36");
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue'),36);checks++;
await as('authenticated',owner);
await db.query("update public.proposal_catalogue set editorial_state='Rascunho' where id=36");
await db.query("insert into public.proposal_progress(proposal_id,stage) values(36,'Realizada')");
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_progress where proposal_id=36'),0);checks++;
await as('authenticated',owner);
await db.query('select public.replace_team($1::jsonb)',[JSON.stringify([{name:'Pessoa de teste',role:'Coordenação autorizada'}])]);
assert.equal(await scalar('select role from public.team_members limit 1'),'Coordenação autorizada');checks++;
await rejects('select public.replace_team($1::jsonb)',[JSON.stringify([{name:'Pessoa de teste',role:'<script>'}])]);
assert.equal(await scalar('select count(*) from public.team_members'),1);checks++;
const ftId=await scalar("insert into public.ft_projects(title,description,category) values('Projeto de teste','Descrição privada de teste','Planejamento') returning id");
assert.equal(await scalar('select count(*) from public.ft_project_history where project_id=$1',[ftId]),1);checks++;
await rejects('insert into public.ft_project_history(project_id,stage,note) values($1,$2,$3)',[ftId,'Concluído','Histórico inventado']);
await rejects('update public.ft_projects set published=true where id=$1',[ftId]);
await as('anon');assert.equal(await scalar('select count(*) from public.ft_projects'),0);assert.equal(await scalar('select count(*) from public.ft_project_history'),0);checks+=2;
await as('authenticated',owner);
await db.query("update public.ft_projects set reviewed=true,published=true,stage='Em análise',update_note='Análise registrada em teste' where id=$1",[ftId]);
assert.equal(await scalar('select count(*) from public.ft_project_history where project_id=$1',[ftId]),2);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.ft_project_history'),2);checks++;
await as('authenticated',student);
await db.query("update public.ft_projects set stage='Concluído' where id=$1",[ftId]);
assert.equal(await scalar('select stage from public.ft_projects where id=$1',[ftId]),'Em análise');checks++;
await as('authenticated',owner);
await db.query("insert into public.management_records(kind,title,body,stage) values('goal','Meta de teste','Planejamento sujeito à aprovação','Proposta sujeita à aprovação')");
await db.query("insert into public.management_records(kind,title,body) values('return','Retorno geral','Resumo revisado sem dados pessoais')");
await rejects("update public.management_records set published=true where kind='return'");
await rejects("insert into public.management_records(kind,title,body,actual_spending) values('decision','Dados inválidos','Valores indevidos fora do orçamento',100)");
await rejects("insert into public.management_records(kind,title,body,actual_spending) values('budget','Valores inválidos','Registro de teste do orçamento',-1)");
await as('anon');assert.equal(await scalar('select count(*) from public.management_records'),0);checks++;
await as('authenticated',owner);
await db.query("update public.management_records set reviewed=true,published=true,stage='Respondida' where kind='return'");
await as('anon');assert.equal(await scalar('select count(*) from public.management_records'),1);checks++;
await rejects('select * from public.suggestions');
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261009_admin_workspace.sql',import.meta.url),'utf8'));
await as('anon');
await rejects('select * from public.management_calendar');
await rejects('select public.create_new_proposal($1::jsonb)',['{}']);
await rejects("select public.set_proposal_editorial(array[36],'Publicada',true)");
await as('authenticated',student);
await rejects('select public.create_new_proposal($1::jsonb)',['{}']);
await rejects("select public.set_proposal_editorial(array[36],'Publicada',true)");
assert.equal(await scalar('select count(*) from public.management_calendar'),0);checks++;
await rejects("insert into public.management_calendar(title,event_date) values('Tentativa sem acesso','2027-01-01')");
await as('authenticated',owner);
const newProposal=await scalar('select public.create_new_proposal($1::jsonb)',[JSON.stringify({title:'Nova proposta de teste',description:'Descrição de uma proposta privada para revisão da equipe.',category:1,editorial_state:'Publicada'})]);
assert.equal(newProposal,46);checks++;
assert.equal(await scalar('select editorial_state from public.proposal_catalogue where id=$1',[newProposal]),'Rascunho');checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications where proposal_id=$1',[newProposal]),1);checks++;
await rejects('select public.create_new_proposal($1::jsonb)',['[]']);
await rejects('select public.create_new_proposal($1::jsonb)',[JSON.stringify({title:'<script>',description:'Conteúdo inválido para cadastro de teste',category:1})]);
await rejects('select public.create_new_proposal($1::jsonb)',[JSON.stringify({title:'Categoria inválida',description:'Conteúdo inválido para cadastro de teste',category:99})]);
await rejects("insert into public.proposal_progress(proposal_id,stage) values(10000,'Apresentada')");
await db.query("insert into public.proposal_progress(proposal_id,stage) values($1,'Em planejamento')",[newProposal]);checks++;
await rejects("select public.set_proposal_editorial(array[46],'Publicada',false)");
await rejects("select public.set_proposal_editorial(array[1,46],'Rascunho',false)");
await rejects("select public.set_proposal_editorial(array[46,10000],'Aprovada pela equipe',false)");
assert.equal(await scalar('select editorial_state from public.proposal_catalogue where id=46'),'Rascunho');checks++;
assert.equal(await scalar("select public.set_proposal_editorial(array[46,46],'Aprovada pela equipe',false)"),1);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue where id=46'),0);checks++;
await as('authenticated',owner);
assert.equal(await scalar("select public.set_proposal_editorial(array[46],'Publicada',true)"),1);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue where id=46'),1);checks++;
await as('authenticated',owner);
const eventId=await scalar("insert into public.management_calendar(title,event_date,proposal_id) values('Reunião de teste','2027-01-15',46) returning id");
assert.equal(await scalar('select stage from public.management_calendar where id=$1',[eventId]),'Proposto');checks++;
await db.query("insert into public.management_calendar(title,event_date,end_date) values('Atividade de teste','2028-02-29','2028-03-01')");checks++;
await rejects("insert into public.management_calendar(title,event_date) values('Fora do período','2026-12-31')");
await rejects("insert into public.management_calendar(title,event_date) values('Fora do período','2029-01-01')");
await rejects("insert into public.management_calendar(title,event_date,end_date) values('Fim inválido','2027-02-02','2027-02-01')");
await rejects("insert into public.management_calendar(title,event_date) values('<script>','2027-01-01')");
await rejects('delete from public.management_calendar where id=$1',[eventId]);
await as('authenticated',student);
assert.equal(await scalar('select count(*) from public.management_calendar'),0);checks++;
await db.query("update public.management_calendar set stage='Concluído' where id=$1",[eventId]);
await as('authenticated',owner);
assert.equal(await scalar('select stage from public.management_calendar where id=$1',[eventId]),'Proposto');checks++;
await db.query("update public.management_calendar set stage='Confirmado' where id=$1",[eventId]);
assert.equal(await scalar('select stage from public.management_calendar where id=$1',[eventId]),'Confirmado');checks++;
assert.equal(await scalar('select count(*) from public.proposal_catalogue where id<=35'),35);checks++;
await as('anon');await rejects('select * from public.management_calendar');
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261009_reversible_proposals.sql',import.meta.url),'utf8'));
await as('anon');await rejects("select public.set_proposal_editorial(array[1],'Rascunho',false)");
await as('authenticated',student);await rejects("select public.set_proposal_editorial(array[1],'Rascunho',false)");
await as('authenticated',owner);
const preserved=await scalar('select row_to_json(p) from public.proposal_catalogue p where id=1');
assert.equal(await scalar("select public.set_proposal_editorial(array[1,36],'Rascunho',false)"),2);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue where id in (1,36)'),0);checks++;
assert.equal(await scalar('select min(id) from public.proposal_catalogue'),2);checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications where proposal_id=1'),0);checks++;
await as('authenticated',owner);
assert.equal(await scalar('select count(*) from public.proposal_catalogue where id<=35'),35);checks++;
await rejects("select public.set_proposal_editorial(array[1],'Publicada',false)");
await rejects("select public.set_proposal_editorial(array[2,10000],'Rascunho',false)");
assert.equal(await scalar('select editorial_state from public.proposal_catalogue where id=2'),'Publicada');checks++;
assert.equal(await scalar("select public.set_proposal_editorial(array[1],'Publicada',true)"),1);checks++;
const restored=await scalar('select row_to_json(p) from public.proposal_catalogue p where id=1');
for(const key of ['id','title','description','category','objective','approach','responsible','authorization_notes'])assert.deepEqual(restored[key],preserved[key]);checks++;
const stage=await scalar('select stage from public.proposal_progress where proposal_id=8');
assert.equal(await scalar("select public.set_proposal_editorial(array[8],'Rascunho',false)"),1);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_progress where proposal_id=8'),0);checks++;
await as('authenticated',owner);
assert.equal(await scalar("select public.set_proposal_editorial(array[8],'Publicada',true)"),1);checks++;
assert.equal(await scalar('select stage from public.proposal_progress where proposal_id=8'),stage);checks++;
assert.equal(await scalar("select public.set_proposal_editorial(array(select id from public.proposal_catalogue),'Rascunho',false)"),46);checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue'),0);checks++;
await as('authenticated',owner);
assert.equal(await scalar("select public.set_proposal_editorial(array(select id from public.proposal_catalogue),'Publicada',true)"),46);checks++;
const roleSource=await readFile(new URL('../assets/js/team-roles.js',import.meta.url),'utf8');
const roles=[...roleSource.matchAll(/title:'([^']+)',key:/g)].map(match=>match[1]);
assert.equal(roles.length,8);checks++;
const team=roles.map((role,index)=>({name:`Pessoa de teste ${index+1}`,role}));
await db.query('select public.replace_team($1::jsonb)',[JSON.stringify(team)]);
assert.deepEqual((await db.query('select name,role from public.team_members order by position')).rows,team);checks++;
await rejects('delete from public.proposal_catalogue where id=1');
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_catalogue'),46);checks++;
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261009_public_calendar.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_site_traffic.sql',import.meta.url),'utf8'));
await as('anon');
assert.equal(await scalar('select count(id) from public.management_calendar'),0);checks++;
await rejects('select description from public.management_calendar');
await rejects('select * from public.site_visits');await rejects('select * from public.site_traffic_daily');await rejects('select public.site_traffic_summary()');
await rejects("select public.record_site_visit(gen_random_uuid(),$1,'index.html',0)",['a'.repeat(64)]);
await as('authenticated',student);await rejects('select public.site_traffic_summary()');
await db.query("update public.proposal_catalogue set approved=true where id=2");
assert.equal(await scalar('select approved from public.proposal_catalogue where id=2'),false);checks++;
await as('authenticated',owner);
await rejects('update public.management_calendar set published=true where id=$1',[eventId]);
await db.query('update public.management_calendar set publication_confirmed=true,published=true,public_description=$2,description=$3,responsible=$4 where id=$1',[eventId,'Descrição pública autorizada de teste','Anotação privada de teste','Responsável privado']);
await db.query('update public.proposal_catalogue set approved=true where id=2');
assert.equal(await scalar('select count(*) from public.proposal_progress where proposal_id=2'),0);checks++;
await as('anon');assert.deepEqual((await db.query('select title,public_description,stage from public.management_calendar')).rows,[{title:'Reunião de teste',public_description:'Descrição pública autorizada de teste',stage:'Confirmado'}]);checks++;
await rejects('select responsible from public.management_calendar');
assert.equal(await scalar('select approved from public.proposal_catalogue where id=2'),true);checks++;
await as('authenticated',owner);
await db.query('update public.management_calendar set published=false where id=$1',[eventId]);
await as('anon');assert.equal(await scalar('select count(id) from public.management_calendar'),0);checks++;
await as('service_role');const visit='00000000-0000-4000-8000-000000000123';
assert.equal(await scalar('select public.record_site_visit($1,$2,$3,$4)',[visit,'a'.repeat(64),'index.html',300]),true);checks++;
assert.equal(await scalar('select active_seconds from public.site_visits where id=$1',[visit]),0);checks++;
await scalar('select public.record_site_visit($1,$2,$3,$4)',[visit,'a'.repeat(64),'index.html',300]);
assert((await scalar('select active_seconds from public.site_visits where id=$1',[visit]))<=2);checks++;
await db.query("update public.site_visits set started_at=now()-interval '120 seconds' where id=$1",[visit]);
await scalar('select public.record_site_visit($1,$2,$3,$4)',[visit,'a'.repeat(64),'index.html',100]);
await scalar('select public.record_site_visit($1,$2,$3,$4)',[visit,'a'.repeat(64),'index.html',10]);
assert.equal(await scalar('select active_seconds from public.site_visits where id=$1',[visit]),100);checks++;
assert.equal(Number(await scalar('select sum(visits) from public.site_traffic_daily')),1);checks++;
assert.equal(Number(await scalar('select sum(active_seconds) from public.site_traffic_daily')),100);checks++;
await rejects('select public.record_site_visit($1,$2,$3,$4)',[visit,'b'.repeat(64),'index.html',110]);
await rejects('select public.record_site_visit(gen_random_uuid(),$1,$2,0)',['a'.repeat(64),'admin/index.html']);
await as('authenticated',owner);
const traffic=await scalar('select public.site_traffic_summary()');assert.equal(traffic.total_visits,1);assert.equal(traffic.week_browsers,1);assert.equal(traffic.average_seconds,100);checks+=3;
await rejects('select * from public.site_visits');
await db.exec('reset role');
const radarBefore=await scalar('select jsonb_agg(to_jsonb(p) order by proposal_id) from public.proposal_progress p');
await db.exec(await readFile(new URL('../supabase/migrations/20261010_radar.sql',import.meta.url),'utf8'));
assert.deepEqual(await scalar("select jsonb_agg(to_jsonb(p)-'completion_percent'-'completion_basis' order by proposal_id) from public.proposal_progress p"),radarBefore);checks++;
assert.equal(await scalar('select count(*) from public.proposal_progress where completion_percent is not null'),0);checks++;
await as('authenticated',owner);
await db.query("insert into public.proposal_progress(proposal_id,stage,completion_percent,completion_basis) values(5,'Em execução',70,'Sete de dez entregas foram concluídas.') on conflict(proposal_id) do update set stage=excluded.stage,completion_percent=excluded.completion_percent,completion_basis=excluded.completion_basis");
await rejects('update public.proposal_progress set completion_percent=101 where proposal_id=5');
await rejects('update public.proposal_progress set completion_percent=-1 where proposal_id=5');
await rejects("update public.proposal_progress set completion_basis='' where proposal_id=5");
await rejects("update public.proposal_progress set completion_basis='<b>Texto indevido</b>' where proposal_id=5");
await rejects('update public.proposal_progress set completion_basis=$1 where proposal_id=5',['a'.repeat(1001)]);
await as('anon');assert.equal(await scalar('select completion_percent from public.proposal_progress where proposal_id=5'),70);checks++;
await rejects('update public.proposal_progress set completion_percent=80 where proposal_id=5');
await as('authenticated',student);await db.query('update public.proposal_progress set completion_percent=80 where proposal_id=5');
assert.equal(await scalar('select completion_percent from public.proposal_progress where proposal_id=5'),70);checks++;
await as('authenticated',owner);await scalar("select public.set_proposal_editorial(array[5],'Rascunho',false)");
await as('anon');assert.equal(await scalar('select count(*) from public.proposal_progress where proposal_id=5'),0);checks++;
await as('authenticated',owner);await scalar("select public.set_proposal_editorial(array[5],'Publicada',true)");
await db.query("update public.proposal_progress set completion_percent=null,completion_basis='' where proposal_id=5");
assert.equal(await scalar('select stage from public.proposal_progress where proposal_id=5'),'Em execução');checks++;
await as('anon');assert.equal(await scalar('select completion_percent from public.proposal_progress where proposal_id=5'),null);checks++;
await db.close();
console.log(`${checks} verificações de PostgreSQL/RLS aprovadas: privacidade, autorização, bloqueios, equipe atômica, duplicação e contagem.`);
