import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const owner = '00000000-0000-4000-8000-000000000001';
const admin = '00000000-0000-4000-8000-000000000002';
const student = '00000000-0000-4000-8000-000000000003';
const hash = 'a'.repeat(64);
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth,public to anon,authenticated,service_role;`);
await db.exec(await readFile(new URL('../supabase/schema.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009_platform.sql', import.meta.url), 'utf8'));
await db.exec(`insert into auth.users values('${owner}'),('${admin}'),('${student}'); insert into public.account_controls(user_id,is_admin,is_owner) values('${owner}',true,true),('${admin}',true,false); insert into public.suggestions(category,message,session_hash) values('Outro','Mensagem de teste privada','${hash}');`);
async function as(role, id = '') { await db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub','${id}',false);`); }
async function rejects(sql, params = []) { await assert.rejects(db.query(sql, params)); checks++; }
async function scalar(sql, params = []) { return Object.values((await db.query(sql, params)).rows[0])[0]; }
await as('anon');
assert.equal(await scalar('select count(*) from public.team_members'), 0); checks++;
assert.equal(await scalar('select count(*) from public.proposal_progress'), 1); checks++;
await rejects('select * from public.suggestions');
await rejects('select * from public.vote_intentions');
await rejects('select public.vote_summary()');
await rejects('select public.record_intention($1)', [hash]);
await rejects('select public.consume_rate($1,1,60)', ['x']);
await rejects("insert into public.team_members(name,position) values('Ataque',0)");
await as('authenticated', student);
assert.equal(await scalar('select count(*) from public.suggestions'), 0); checks++;
await rejects('select public.replace_team($1::jsonb)', ['["Ataque"]']);
await rejects('select public.vote_summary()');
await rejects('update public.account_controls set is_admin=true where user_id=$1', [student]);
await db.query("insert into public.proposal_progress(proposal_id,stage) values(1,'Realizada')").then(() => { throw new Error('Unauthorized mutation succeeded'); }, () => checks++);
await as('authenticated', admin);
assert.equal(await scalar('select count(*) from public.suggestions'), 1); checks++;
await db.query('select public.replace_team($1::jsonb)', ['["Nome autorizado de teste","Outro nome autorizado"]']); checks++;
assert.equal(await scalar('select count(*) from public.team_members'), 2); checks++;
await rejects('select public.replace_team($1::jsonb)', ['["<script>"]']);
assert.equal(await scalar('select count(*) from public.team_members'), 2); checks++;
await rejects("update public.suggestions set message='Conteúdo alterado'");
await db.query("update public.suggestions set status='analisada'"); checks++;
await rejects('select public.manage_account($1,true,false,null,$2)', [student, 'Permissão de teste']);
await as('service_role');
const results = await Promise.all(Array.from({ length: 10 }, () => scalar('select public.record_intention($1)', [hash])));
assert.equal(results.filter(Boolean).length, 1); checks++;
assert.equal(await scalar('select count(*) from public.vote_intentions'), 1); checks++;
assert.equal(await scalar('select public.consume_rate($1,1,60)', ['test-bucket']), true); checks++;
assert.equal(await scalar('select public.consume_rate($1,1,60)', ['test-bucket']), false); checks++;
await as('authenticated', owner);
const summary = await scalar('select public.vote_summary()');
assert.equal(summary.ft_intentions, 1); assert.equal(summary.student_total, 310); assert.equal(summary.opposition_reported, 80); assert.equal(summary.unrepresented_estimate, 229); checks += 4;
await db.query('select public.manage_account($1,true,true,null,$2)', [admin, 'Bloqueio justificado de teste']); checks++;
await rejects('select public.manage_account($1,false,true,null,$2)', [owner, 'Tentativa de alterar proprietário']);
await as('authenticated', admin);
assert.equal(await scalar('select public.is_admin()'), false); checks++;
assert.equal(await scalar('select count(*) from public.suggestions'), 0); checks++;
await rejects('select public.vote_summary()');
await as('authenticated', owner);
await db.query('select public.suspend_session($1,now()+interval\'1 day\',$2)', [hash, 'Spam de teste']); checks++;
await rejects('select public.suspend_session($1,now()+interval\'31 days\',$2)', [hash, 'Tempo inválido']);
await rejects("insert into public.proposal_progress(proposal_id,stage) values(36,'Apresentada')");
await as('anon');
assert.equal(await scalar('select count(*) from public.proposal_classifications where priority'), 5); checks++;
assert.equal(await scalar('select count(*) from public.proposal_classifications where early'), 8); checks++;
await rejects('select * from public.election_2026');
await rejects('select public.save_election($1,true)', ['{"status":"eleita"}']);
await as('authenticated',student);
await db.query('update public.proposal_classifications set priority=true where proposal_id=31');
assert.equal(await scalar('select priority from public.proposal_classifications where proposal_id=31'),false);checks++;
await rejects("insert into public.project_records(kind,category,title,description) values('talentos','Música','Teste','Trabalho privado de teste')");
await as('authenticated',owner);
await db.query("insert into public.project_records(kind,category,title,description) values('talentos','Música','Rascunho','Trabalho privado de teste')");checks++;
await rejects("update public.project_records set published=true");
await as('anon');
assert.equal(await scalar('select count(*) from public.project_records'),0); checks++;
const hidden=await scalar('select public.election_public()');
if(Date.now()<Date.parse('2026-10-13T03:00:00Z')){assert.equal(hidden.visible,false);assert.equal(hidden.intentions,undefined);checks+=2;}
await as('authenticated',owner);
await db.query("update public.project_records set consent_confirmed=true,published=true");checks++;
await as('anon');assert.equal(await scalar('select count(*) from public.project_records'),1);checks++;
await as('authenticated',owner);
await rejects('select public.save_election($1,true)',['{"status":"eleita","source":"Escola"}']);
await as('service_role');
await db.query("update public.election_2026 set status='eleita',confirmed_at=now(),source='Registro de teste da escola',published_at=now()");
await rejects('select public.record_intention($1)',['b'.repeat(64)]);
assert.equal(await scalar('select count(*) from public.vote_intentions'),1); checks++;
await db.close();
console.log(`${checks} verificações de PostgreSQL/RLS aprovadas: privacidade, autorização, bloqueios, equipe atômica, duplicação e contagem.`);
