const env=(name:string)=>{const value=Deno.env.get(name);if(!value)throw Error('Configuration unavailable');return value;};
async function digest(value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env('ABUSE_HASH_SECRET')),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');}
async function rpc(name:string,body:unknown){const key=env('SUPABASE_SERVICE_ROLE_KEY');const result=await fetch(env('SUPABASE_URL')+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});if(!result.ok)throw Error('Database unavailable');return result.json();}
Deno.serve(async(req:Request)=>{
 const origin=req.headers.get('origin')||'';const allowed=(Deno.env.get('ALLOWED_ORIGINS')||'').split(',').map(value=>value.trim());const headers={'Access-Control-Allow-Origin':allowed.includes(origin)?origin:'null','Access-Control-Allow-Headers':'content-type,apikey,authorization','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'};const reply=(status:number,value:unknown)=>new Response(JSON.stringify(value),{status,headers});
 if(!allowed.includes(origin))return reply(403,{received:false});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return reply(405,{received:false});if(!req.headers.get('content-type')?.startsWith('application/json'))return reply(415,{received:false});
 try{
  const reader=req.body?.getReader();if(!reader)return reply(400,{received:false});const chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>2048){await reader.cancel();return reply(413,{received:false});}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}let input;try{input=JSON.parse(new TextDecoder().decode(bytes));}catch{return reply(400,{received:false});}
  const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;const pages=['index.html','catalogo.html','propostas.html','gestao.html','proposta.html','projetos.html','calendario.html','faq.html','eleicoes.html','planejamento.html','historia.html','gremio.html','bem-estar.html','infraestrutura.html','privacidade.html','404.html'];if(!input||typeof input!=='object'||!uuid.test(input.visit||'')||!uuid.test(input.browser||'')||!Number.isInteger(input.seconds)||input.seconds<0||input.seconds>43200||!pages.includes(input.page))return reply(400,{received:false});
  const visitHash=await digest('traffic-visit:'+input.visit);const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';const ipHash=await digest('traffic-ip:'+ip);const sessionAllowed=await rpc('consume_rate',{bucket_key:'traffic:visit:'+visitHash,max_hits:24,window_seconds:600});const ipAllowed=await rpc('consume_rate',{bucket_key:'traffic:ip:'+ipHash,max_hits:10000,window_seconds:600});if(!sessionAllowed||!ipAllowed)return reply(429,{received:false});
  await rpc('record_site_visit',{visit_id:input.visit,browser_hash:await digest('traffic-browser:'+input.browser),target_page:input.page,seconds:input.seconds});return reply(200,{received:true});
 }catch{return reply(503,{received:false});}
});
